### ISSUE TITLE
[mod-init] Curl/JQ was not found on this system for Docker mods installing

### ISSUE THREAD

**Issue by mali1** [linuxserver/docker-paperless-ngx#27]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
I want to use https://github.com/linuxserver/docker-mods/tree/papermerge-multilangocr as described in https://github.com/linuxserver/docker-paperless-ngx/issues/5 
After trying to add the dockermod I got the following error during the start of the container

[mod-init] Curl/JQ was not found on this system for Docker mods installing

**Comment by Roxedus** [comment]
Post full logs please
