### ISSUE TITLE
Using a reverse proxy fails with error "CSRF verification failed"

### ISSUE THREAD

**Issue by gigabit942007** [linuxserver/docker-paperless-ngx#28]
There is a bug that requires an environment variable to be set:
PAPERLESS_URL

If you do not set this variable then you can't use a reverse proxy.
https://github.com/paperless-ngx/paperless-ngx/issues/817

Error:
![image](https://user-images.githubusercontent.com/8338004/177360539-7dd146ca-1503-4b2b-ba40-a5df9406dbf6.png)

Settings this environment variable does not resolve the issue, possible something else has to be done additionally.

**Comment by k4j8** [comment]
I had this error as well when updating to version 1.7.1, but adding an environment variable and then taking the service down and then back up fixed it (restarting did NOT work).

`docker-compose.yml`:
```yaml
version: "2.1"
services:
  paperless-ngx:
    ...
    env_file: docker-compose.env
```
`docker-compose.env` (no trailing slash in URL):
```yaml
PAPERLESS_URL=https://paperless.yourdomain.com
```

I'm not experienced with this stuff - just sharing what worked for me.

(Updated to mention trailing slash issue.)

**Comment by gigabit942007** [comment]
I do not use docker-compose and adding the environment variable unfortunately does not fix the issue for me, maybe it's ignored if the image is used in Kubernetes?

**Comment by lukyjay** [comment]
> I had this error as well when updating to version 1.7.1, but adding an environment variable and then taking the service down and then back up fixed it (restarting did NOT work).
> 
> `docker-compose.yml`:
> 
> ```yaml
> version: "2.1"
> services:
>   paperless-ngx:
>     ...
>     env_file: docker-compose.env
> ```
> 
> `docker-compose.env`:
> 
> ```yaml
> PAPERLESS_URL=your_URL_here
> ```
> 
> I'm not experienced with this stuff - just sharing what worked for me.

Thanks so much - fixed it for me. Worth noting the URL needs to be in this format: https://paperless.yourdomain.com (no trailing slash)

**Comment by gigabit942007** [comment]
FSent from my Galaxy
-------- Original message --------From: Jayden ***@***.***> Date: 24/07/2022  11:48  (GMT+02:00) To: linuxserver/docker-paperless-ngx ***@***.***> Cc: gigabit942007 ***@***.***>, Author ***@***.***> Subject: Re: [linuxserver/docker-paperless-ngx] Using a reverse proxy fails with error "CSRF verification failed" (Issue #28) 

I had this error as well when updating to version 1.7.1, but adding an environment variable and then taking the service down and then back up fixed it (restarting did NOT work).
docker-compose.yml:
version: "2.1"
services:
  paperless-ngx:
    ...
    env_file: docker-compose.env
docker-compose.env:
PAPERLESS_URL=your_URL_here
I'm not experienced with this stuff - just sharing what worked for me.

Thanks so much - fixed it for me. Worth noting the URL needs to be in this format: https://paperless.yourdomain.com (no trailing slash)
