### ISSUE TITLE
Could you please add the package in public ? Thanks :-)

### ISSUE THREAD

**Issue by alexbelgium** [linuxserver/docker-paperless-ngx#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Pulling "lscr.io/linuxserver/paperless-ngx:arm64v8-latest" should get the latest image.

## Current Behavior
It works with dockerhub image, but fails with ghcr ones (Head "https://ghcr.io/v2/linuxserver/paperless-ngx/manifests/arm32v7-latest": unauthorized)

## Steps to Reproduce
1. Use an incognito browser page, or a browser without being logged
2. Go to https://ghcr.io/v2/linuxserver/paperless-ngx/manifests/arm32v7-latest

## Environment
**OS:** Linux
**CPU architecture:** aarch64
**How docker service was installed:** Using Home Assistant OS

**Comment by aptalca** [comment]
Done

**Comment by alexbelgium** [comment]
Thanks very much, and for providing this images for paperless ngx. Linuxserver rocks ;-)
