### ISSUE TITLE
(Default) User Account

### ISSUE THREAD

**Issue by adit-s** [linuxserver/docker-paperless-ngx#4]
Hello. Thank you for creating an image for paperless-ngx. It will be very useful to me and I'm sure a lot of people.
I set up the containers using the docker run method (since I'm not that familiar with docker-compose). 
Everything looks like it worked like it should, but I can't figure out how to login or create the default admin account. I've read through the docs and tried a few things but nothing worked. I found a method using docker-compose but since I'm using the docker run method wasn't able to try it. Do you have any suggestions or ideas?

Thanks in advance,
Adit

**Comment by tobbenb** [comment]
This is not a support forum. For support please use Discord or our discourse forum. You can find the links here https://www.linuxserver.io/support

The answer to your question is in the readme, which tells you the default username and password.

**Comment by adit-s** [comment]
So sorry. My mistake. I am trying paperless-ngx for the first time and was going through all the docs to figure out how to make the OCR work with Word docs and ended up not reading your docker container Read Me carefully enough and missed that info. You can delete this issue if you like. Thanks again for building an easy to deploy image. I'm sure many people will use it.
