### ISSUE TITLE
Migration from paperless-ng fails, because language is not installed

### ISSUE THREAD

**Issue by andrelung** [linuxserver/docker-paperless-ngx#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
As mentioned in the official documentation, ngx should be a "drop-in replacement for Paperless-ng and thus upgrading should be trivial for most users". Sadly it isn't for me 🙃

## Current Behavior
I am using unraid as the docker host and haven't found an option to set PAPERLESS_OCR_LANGUAGE or PAPERLESS_OCR_LANGUAGES via variables. This is the error:

`The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE`

## Steps to Reproduce

1. install old paperless-ng via docker https://github.com/jonaswinkler/paperless-ng
2. set German language via variable
3. replace the url as mentioned in the migration-documentation: https://paperless-ngx.readthedocs.io/en/latest/setup.html#migrating-from-paperless-ng
4. try to open your migrated ngx / logs

## Environment
**OS:** Unraid OS 6.9.2
**CPU architecture:** x86_64
**How docker service was installed:** out-of-the-box OS provided

## Command used to create docker container (run/create/compose/screenshot)
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='paperless-ngx' --net='bridge' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PAPERLESS_REDIS'='redis://:941378@192.168.xx.xx:6379' -e 'PAPERLESS_OCR_LANGUAGE'='deu' -e 'PAPERLESS_OCR_LANGUAGES'='deu' -e 'PAPERLESS_FILENAME_FORMAT'='{created}-{correspondent}-{title}' -e 'PAPERLESS_TIME_ZONE'='Europe/Berlin' -e 'PAPERLESS_IGNORE_DATES'='' -e 'PAPERLESS_CONSUMER_POLLING'='0' -e 'PAPERLESS_SECRET_KEY'='notimportant' -e 'USERMAP_UID'='99' -e 'USERMAP_GID'='100' -p '8301:8000/tcp' -v '/mnt/user/appdata/paperless-ng/data':'/usr/src/paperless/data':'rw' -v '/mnt/user/appdata/paperless-ng/media':'/usr/src/paperless/media':'rw' -v '/mnt/user/scannedDocuments/':'/usr/src/paperless/consume':'rw' -v '/mnt/user/appdata/paperless-ng/export':'/usr/src/paperless/export':'rw' 'lscr.io/linuxserver/paperless-ngx'

## Docker logs

> os: Linux-5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021
> nodename: c1f640325733
> machine: x86_64
> clock source: unix
> pcre jit disabled
> detected number of CPU cores: 8
> current working directory: /app/paperless/src
> detected binary path: /usr/bin/uwsgi-core
> your processes number limit is 256306
> your memory page size is 4096 bytes
> detected max file descriptor number: 40960
> building mime-types dictionary from file /etc/mime.types...567 entry found
> lock engine: pthread robust mutexes
> thunder lock: disabled (you can enable it with --thunder-lock)
> uwsgi socket 0 bound to TCP address :8000 fd 3
> Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
> 
> Python main interpreter initialized at 0x55cd0c9801d0
> python threads support enabled
> your server socket listen backlog is limited to 100 connections
> your mercy for graceful operations on workers is 60 seconds
> mapped 145840 bytes (142 KB) for 1 cores
> *** Operational MODE: single process ***
> running "exec:/usr/bin/python3 /app/paperless/src/manage.py collectstatic --noinput" (pre app)...
> 
> 166 static files copied to '/app/paperless/static', 277 unmodified.
> running "exec:/usr/bin/python3 /app/paperless/src/manage.py compilemessages" (pre app)...
> File “/app/paperless/src/locale/km_KH/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/sl_SI/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/no_NO/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/pl_PL/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/cs_CZ/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/th_TH/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/nb_NO/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/ru_RU/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/ko_KR/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/da_DK/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/ar_EG/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/lb_LU/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/it_IT/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/ar_BH/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/en_GB/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/es_ES/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/xh_ZA/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/la_LA/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/ar_SA/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/en_US/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/nl_NL/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/he_IL/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/pt_PT/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/zh_TW/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/el_GR/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/pt_BR/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/fr_FR/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/hu_HU/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/sv_SE/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/ro_RO/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/zh_CN/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/ar_YE/LC_MESSAGES/django.po” is already compiled and up to date.
> File “/app/paperless/src/locale/de_DE/LC_MESSAGES/django.po” is already compiled and up to date.
> WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55cd0c9801d0 pid: 355 (default app)
> *** uWSGI is running in multiple interpreter mode ***
> spawned uWSGI master process (pid: 355)
> spawned uWSGI worker 1 (pid: 390, cores: 1)
> [uwsgi-daemons] spawning "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" (uid: 911 gid: 911)
> [uwsgi-daemons] spawning "/usr/bin/python3 /app/paperless/src/manage.py qcluster" (uid: 911 gid: 911)
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
> [uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" for 1 seconds
> [uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py qcluster" for 1 seconds
> [uwsgi-daemons] respawning "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" (uid: 911 gid: 911)
> [uwsgi-daemons] respawning "/usr/bin/python3 /app/paperless/src/manage.py qcluster" (uid: 911 gid: 911)
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
> [uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" for 1 seconds
> [uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py qcluster" for 1 seconds
> [uwsgi-daemons] respawning "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" (uid: 911 gid: 911)
> [uwsgi-daemons] respawning "/usr/bin/python3 /app/paperless/src/manage.py qcluster" (uid: 911 gid: 911)
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
> [uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py document_consumer" for 1 seconds
> [uwsgi-daemons] throttling "/usr/bin/python3 /app/paperless/src/manage.py qcluster" for 1 seconds
> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> ?: The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.

**Comment by aptalca** [comment]
we have a mod for language packages: https://github.com/linuxserver/docker-mods/tree/papermerge-multilangocr

**Comment by darkmattercoder** [comment]
With the mentioned mod, the German OCR works perfectly fine with the image. I use that within my setup. Just make sure you set both the `OCRLANG` and the `PAPERLESS_OCR_LANGUAGE` variables.

**Comment by andrelung** [comment]
Thank you, that works! 

After messing around, I also found a direct replacement on my hosts app-platform:
https://forums.unraid.net/topic/121075-support-paperless-ngx-docker/
