### ISSUE TITLE
webui connection reset

### ISSUE THREAD

**Issue by kjames2001** [linuxserver/docker-paperless-ngx#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

paperless ngx docker not working on unraid, 
## Current Behavior

connection reset when opening webui.
## Steps to Reproduce

1.install paperless ngx docker from CA
2.
3.
4.

## Environment
**OS:** Unraid
**CPU architecture:** x86_64
**How docker service was installed:** 

From CA using default parameters, except port mapping
## Docker logs

21:02:06 [Q] INFO Process-1:1 ready for work at 439
21:02:06 [Q] INFO Process-1:2 ready for work at 440
21:02:06 [Q] INFO Process-1:3 ready for work at 441
21:02:06 [Q] INFO Process-1:4 ready for work at 442
21:02:06 [Q] INFO Process-1:5 monitoring at 443
21:02:06 [Q] INFO Process-1 guarding cluster zulu-hot-jupiter-four
21:02:06 [Q] INFO Process-1:6 pushing tasks at 444
21:02:06 [Q] INFO Q Cluster zulu-hot-jupiter-four running.
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
21:02:36 [Q] INFO Enqueued 1
21:02:36 [Q] INFO Process-1 created a task from schedule [Train the classifier]
21:02:36 [Q] INFO Process-1:1 processing [eight-pluto-nuts-montana]
21:02:36 [Q] INFO Enqueued 1
21:02:36 [Q] INFO Process-1 created a task from schedule [Optimize the index]
21:02:36 [Q] INFO Process-1:2 processing [papa-oranges-arizona-earth]
21:02:36 [Q] INFO Enqueued 1
21:02:36 [Q] INFO Process-1 created a task from schedule [Perform sanity check]
21:02:36 [Q] INFO Enqueued 1
21:02:36 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
21:02:36 [Q] INFO Process-1:3 processing [leopard-echo-bacon-uniform]
21:02:36 [Q] INFO Process-1:4 processing [oklahoma-cat-seventeen-jersey]
21:02:36 [Q] INFO Process-1:4 stopped doing work
21:02:36 [Q] INFO Processed [oklahoma-cat-seventeen-jersey]
21:02:36 [Q] INFO Process-1:1 stopped doing work
[2022-04-05 21:02:36,490] [INFO] [paperless.sanity_checker] Sanity checker detected no issues.
21:02:36 [Q] INFO Process-1:3 stopped doing work
21:02:36 [Q] INFO Process-1:2 stopped doing work
21:02:36 [Q] INFO Processed [eight-pluto-nuts-montana]
21:02:36 [Q] INFO Processed [leopard-echo-bacon-uniform]
21:02:36 [Q] INFO Processed [papa-oranges-arizona-earth]
21:02:36 [Q] INFO recycled worker Process-1:1
21:02:36 [Q] INFO Process-1:7 ready for work at 451
21:02:36 [Q] INFO recycled worker Process-1:3
21:02:36 [Q] INFO Process-1:8 ready for work at 452
21:02:37 [Q] INFO recycled worker Process-1:2
21:02:37 [Q] INFO Process-1:9 ready for work at 453
21:02:37 [Q] INFO recycled worker Process-1:4
21:02:37 [Q] INFO Process-1:10 ready for work at 454
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip
invalid HTTP request size (max 4096)...skip

**Comment by stumpylog** [comment]
The error at least is coming from gunicorn: https://docs.gunicorn.org/en/stable/settings.html#limit-request-line

So something in your environment is making large request to the server, which rejects them.  Perhaps a browser extension?
